config/routes.rb
Noo::Application.routes.draw do

  resources :goals
  resources :stack_images
  resources :stacks
  resources :ingredients 

  devise_for :users do 

  end

  
  

 get 'users/:user' => 'stacks#by_user'

 get '/images' => 'stacks#get_images'
 get '/list' => 'stacks#index'

  root :to => 'stacks#hotness'
    

end

app/models/stack.rb
class Stack < ActiveRecord::Base
  default_scope order('created_at DESC')

  #relationships
  has_many :ingredients,:dependent => :destroy
  has_many :stack_images, :dependent => :destroy
  has_many :goals, :dependent => :destroy
  #
  accepts_nested_attributes_for :ingredients, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :stack_images, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :goals, :reject_if => lambda { |a| a[:description].blank? }, :allow_destroy => true


  attr_accessible :description, :name, :user_id, :featured,
    #mass
    :ingredients_attributes,:stack_images_attributes, :goals_attributes

  validates_presence_of :name, :description
  

  #SCOPES
  scope :featured, where(featured: true)

end

class String
  def is_number?
    true if Float(self) rescue false
  end
end

app/controllers/stacks_controller.rb
require 'net/http'
require 'json'

class StacksController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :new]

  def hotness
    @featured = Stack.featured
  end
  
  def by_user
   if params[:user].is_number? #find by users id or screen name
    # raise "int"
      @stacks_by_user = Stack.find_all_by_user_id(params[:user])
   else
      @stack = Stack.find_by_user_id(User.find_by_username("params[:user]"))
      @stacks_by_user = Stack.find_all_by_user_id(User.find_by_username(params[:user]))
   end  
  end

  def index
    @stacks = Stack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stacks }
    end
  end

  # GET /stacks/1
  # GET /stacks/1.json
  def show
    @stack = Stack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stack }
    end
  end

  # GET /stacks/new
  # GET /stacks/new.json
  def new
    @stack = Stack.new 
    2.times {@stack.ingredients.build}
    1.times {@stack.stack_images.build}
    1.times {@stack.goals.build}
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stack }
    end
  end

  def get_images
     _name            = params[:name] ? params[:name] : "failure"
    _url              = "http://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=#{_name.gsub(' ','%20')}"
    _response         = Net::HTTP.get_response(URI.parse(_url))
    _response_hash    = JSON.parse _response.body
    _structure         =  _response_hash.deep_symbolize_keys 
    @stack_imgs       = _structure[:responseData][:results].map { |r| r["url"]}

    render json: {
      data: {
        images: @stack_imgs
      }
    }
  end


  # GET /stacks/1/edit
  def edit
    @stack = Stack.find(params[:id])
  end

  # POST /stacks
  # POST /stacks.json
  def create
    @stack = Stack.new(params[:stack])

    # 2.times {@stack.ingredients.build}
    # 1.times {@stack.stack_images.build}


    respond_to do |format|
      if @stack.save
        format.html { redirect_to @stack, notice: 'Stack was successfully created.' }
        format.json { render json: @stack, status: :created, location: @stack }
      else
        format.html { render action: "new" }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stacks/1
  # PUT /stacks/1.json
  def update
    @stack = Stack.find(params[:id])

    respond_to do |format|
      if @stack.update_attributes(params[:stack])
        format.html { redirect_to @stack, notice: 'Stack was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stacks/1
  # DELETE /stacks/1.json
  def destroy
    @stack = Stack.find(params[:id])
    @stack.destroy

    respond_to do |format|
      format.html { redirect_to stacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stacks_helper.rb
module StacksHelper
end

app/views/stacks/_form.html.erb
<%= form_for(@stack) do |f| %>
  <% if @stack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stack.errors.count, "error") %> please check red fields:</h2>

      <ol>
      <% @stack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ol>
    </div>
  <% end %>


<% if  user_signed_in?  && current_user.username == "jahrichie" %>
<table style="background:transparent;border:0;">
  <td><%= f.label :featured, :style => 'margin-top:5px;' %></td>
  <td><%= f.check_box :featured  %></td>
</table>
<% end %>   


  <div class="field cf">
   <%= f.text_field :name, :class => "required", :placeholder => 'Name' %>
  </div>
  <div class="field cf">
    <%= f.text_area :description, :class => "required", :placeholder => 'Description' %>
  </div>


<div id="stack-images">
  <!-- <h1 class="images-header">Images</h1> -->

<div class="stack-images-inputs">  
  <%= f.fields_for :stack_images do |i| %>
   <div class="field cf">

   </div>
  <% end %>
</div>


</div>

<h1 class="ingredients-header">Ingreditents</h1>

<div class="ingredients">  
  
    <%= f.fields_for :ingredients do |i| %>
      <table id="ingredients">
       <div class="field cf">
          <tr>
            <td><%= i.text_field :name, :rows => 3 ,:placeholder => 'Ingredient Name', :class => "required"%> </td>
            <td><%= i.text_field :percentage,   :placeholder => 'Percentage',:class => 'Percentage required' %>
            </td>
          </tr>
               </div>
      </table>
    <% end %>

</div>



  <p class="add-link"><%= link_to_add_fields "<i class='icon-plus'></i> Add Ingedient".html_safe, f, :ingredients %></p>



<div class="goals-inputs">  
  <h1 class="goals-header">Stack Goals</h1>  
  <%= f.fields_for :goals do |i| %>
     <%= i.text_field :description, :rows => 3 , :placeholder => 'Goal Description', :class => "required"%> 
  <% end %>
</div>
  <p class="add-link"><%= link_to_add_goals "<i class='icon-plus'></i> Add Goals".html_safe, f, :goals %></p>

  <!-- foo -->

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit :class => "button" %>
  </div>
<% end %>

app/views/stacks/by_user.slim
h1 Listing stacks

table
  tr
    th 
    th Name
    th Goals
    th Ingredients
    th 
    th
    th
  - @stacks_by_user.each do |stack|
    tr
      - _images = stack.stack_images.map{|i| i[:url]}
      td.thumb  
        = link_to image_tag(_images.sample), stack, :style => "border: 5px solid #000;display:inline-block;"
        
      / span style="background:#000;" = StackImage.find_all_by_stack_id(stack).size
      td= stack.name
      td= stack.goals.map{|g| g.description}.to_sentence if stack.goals 
      - _ingredients = stack.ingredients.map{|i| i[:name]}
      td.ingredients-yo  
        - _ingredients.each do |i| 
          - _p = Ingredient.find_by_name(i).percentage
          - _p = number_to_percentage(_p, precision: 0)



          div.has-tip.tip-top.ingredient-tag data-tooltip="data-tooltip" title="#{i}" data-percentage="#{_p}" style="background:#{random_neons};" = _p
          

          / span data-tooltip="data-tooltip=" class="has-tip"  data-percentage="#{_p}"  title="#{i}"  asdasd







      / _ingredients.present? ? _ingredients : "Blank"
      - if user_signed_in?  && stack.user_id == current_user.id
        td= link_to 'Show', stack
        td= link_to 'Edit', edit_stack_path(stack)
        td= link_to 'Destroy', stack, method: :delete, confirm: 'Are you sure?' 
      /! users.map{|u| u[:email]}
br

app/views/stacks/edit.html.erb
<h1>Editing stack</h1>

<%= render 'form' %>

<%= link_to 'Show', @stack %> |
<%= link_to 'Back', stacks_path %>

app/views/stacks/hotness.slim
.cf
ul.orbit-featured data-orbit=""
  - @featured.each do |feat|
    li
      .this-stack
        - feat.ingredients.each do |ing|
          - _top_range = AppStyle::BACKGROUND_AND_FONT.size
          = stack_representation(ing,_top_range).html_safe    
      .orbit-caption = feat.name

app/views/stacks/index.slim
h1 Listing stacks

table
  tr
    th 
    th Author
    th Name
    th Goals
    th Ingredients
    th 
    th
    th
  - @stacks.each do |stack|
    tr
      - _images = stack.stack_images.map{|i| i[:url]}
      td.thumb  
        = link_to image_tag(_images.sample), stack, :style => "border: 5px solid #000;display:inline-block;"
        
      / span style="background:#000;" = StackImage.find_all_by_stack_id(stack).size
      td= User.find(stack.user_id).username
      td= stack.name
      td= stack.goals.map{|g| g.description}.to_sentence if stack.goals 
      - _ingredients = stack.ingredients.map{|i| i[:name]}
      td.ingredients-yo  
        - _ingredients.each do |i| 
          - _p = Ingredient.find_by_name(i).percentage
          - _p = number_to_percentage(_p, precision: 0)



          div.has-tip.tip-top.ingredient-tag data-tooltip="data-tooltip" title="#{i}" data-percentage="#{_p}" style="background:#{random_neons};" = _p
          

          / span data-tooltip="data-tooltip=" class="has-tip"  data-percentage="#{_p}"  title="#{i}"  asdasd







      / _ingredients.present? ? _ingredients : "Blank"
      - if user_signed_in?  && stack.user_id == current_user.id
        td= link_to 'Show', stack
        td= link_to 'Edit', edit_stack_path(stack)
        td= link_to 'Destroy', stack, method: :delete, confirm: 'Are you sure?' 
      /! users.map{|u| u[:email]}
br

app/views/stacks/new.html.erb
<h1>New stack</h1>

 
<%= render 'form' %>

<%= link_to 'Back', stacks_path %>

app/views/stacks/show.html.erb
<p id="notice"><%= notice %></p>

 <% if user_signed_in?  && current_user.id == @stack.user_id %> 
  <div class="button edit-this-stack cf">
    <%= link_to 'Edit', edit_stack_path(@stack) %> 
  </div>
 <% end  %>

<h1><%= @stack.name %></h1>

<h3>Goals</h3>
<ol id="goals">
  <% for goal in @stack.goals %> 
    <li><%= goal.description %></li>
  <% end  %>
</ol>


<h3>ingredients</h3>
<div class="this-stack">
  <% for ingredient in @stack.ingredients %> 
  <% _top_range = AppStyle::BACKGROUND_AND_FONT.size %>
    <%= stack_representation(ingredient,_top_range).html_safe %>
  <% end  %>
</div>

<div class="ingredient-dials-wrapper cf">  
  <% for ingredient in @stack.ingredients %>
    <span class="chart" data-percent="<%=  ingredient.percentage %>">
      <%=  ingredient.percentage %>%
    </span>
   
  <div class="label"><%= h ingredient.name %></div>
  <% end %>
</div>
 



<p style="clear:both">
  <h3>Description</h3>
  <%= @stack.description %>
</p>


<% if  @stack.stack_images.count > 0  %>
  <h3>images</h3>
   <div class="stack-all-images-wrapper">
     <% for image in @stack.stack_images %>
       <div class="stack-images-wrapper">
         <%= h image_tag image.name, :class => 'google-image-show' %></li>
         <%= link_to 'Destroy', image, class: 'image-destroyer',method: :delete, data: { confirm: 'Are you sure?' } %>
       </div>
     <% end %>
    </div>
<% end %>