config/routes.rb
Noo::Application.routes.draw do

  resources :goals
  resources :stack_images
  resources :stacks
  resources :ingredients 

  devise_for :users do 

  end

  
  

 get 'users/:user' => 'stacks#by_user'

 get '/images' => 'stacks#get_images'
 get '/list' => 'stacks#index'

  root :to => 'stacks#hotness'
    

end

app/models/stack_image.rb
class StackImage < ActiveRecord::Base
  attr_accessible :name, :stack_id, :url

  #relationships
  belongs_to :stack
end

app/controllers/stack_images_controller.rb
class StackImagesController < ApplicationController
  # GET /stack_images
  # GET /stack_images.json
  def index
    @stack_images = StackImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stack_images }
    end
  end

  # GET /stack_images/1
  # GET /stack_images/1.json
  def show
    @stack_image = StackImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stack_image }
    end
  end

  # GET /stack_images/new
  # GET /stack_images/new.json
  def new
    @stack_image = StackImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stack_image }
    end
  end

  # GET /stack_images/1/edit
  def edit
    @stack_image = StackImage.find(params[:id])
  end

  # POST /stack_images
  # POST /stack_images.json
  def create
    @stack_image = StackImage.new(params[:stack_image])

    respond_to do |format|
      if @stack_image.save
        format.html { redirect_to @stack_image, notice: 'Stack image was successfully created.' }
        format.json { render json: @stack_image, status: :created, location: @stack_image }
      else
        format.html { render action: "new" }
        format.json { render json: @stack_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stack_images/1
  # PUT /stack_images/1.json
  def update
    @stack_image = StackImage.find(params[:id])

    respond_to do |format|
      if @stack_image.update_attributes(params[:stack_image])
        format.html { redirect_to @stack_image, notice: 'Stack image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stack_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stack_images/1
  # DELETE /stack_images/1.json
  def destroy
    @stack_image = StackImage.find(params[:id])
    @stack_image.destroy

    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end
end

app/helpers/stack_images_helper.rb
module StackImagesHelper
end

app/views/stack_images/_form.html.erb
<%= form_for(@stack_image) do |f| %>
  <% if @stack_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stack_image.errors.count, "error") %> prohibited this stack_image from being saved:</h2>

      <ul>
      <% @stack_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :stack_id %><br />
    <%= f.number_field :stack_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stack_images/edit.html.erb
<h1>Editing stack_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @stack_image %> |
<%= link_to 'Back', stack_images_path %>

app/views/stack_images/index.html.erb
<h1>Listing stack_images</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Stack</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stack_images.each do |stack_image| %>
  <tr>
    <td><%= stack_image.name %></td>
    <td><%= stack_image.stack_id %></td>
    <td><%= stack_image.url %></td>
    <td><%= link_to 'Show', stack_image %></td>
    <td><%= link_to 'Edit', edit_stack_image_path(stack_image) %></td>
    <td><%= link_to 'Destroy', stack_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stack image', new_stack_image_path %>

app/views/stack_images/new.html.erb
<h1>New stack_image</h1>

<%= render 'form' %>

<%= link_to 'Back', stack_images_path %>

app/views/stack_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @stack_image.name %>
</p>

<p>
  <b>Stack:</b>
  <%= @stack_image.stack_id %>
</p>

<p>
  <b>Url:</b>
  <%= @stack_image.url %>
</p>


<%= link_to 'Edit', edit_stack_image_path(@stack_image) %> |
<%= link_to 'Back', stack_images_path %>